import { Alumno } from "../models/alumno";

export const alumnos = {
    obtenerCursos: () => {
        return [
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Pedro',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            },
            {nombre:'Angel',
            apellido:'Perez',
            inscripcionAbierta:true,
            edad:21,
            sexo:'Hombre',
            validado:true
            }]
    }
}